# Numpy 
NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

In [1]:
#import module
import numpy as np

In [2]:
#checking numpy version
print(np.__version__)

1.21.5


<br>

## Creating Numpy Array
<hr>

In [3]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [4]:
print(type(arr))

<class 'numpy.ndarray'>


### 0 Dimension Array

In [5]:
dim0 = np.array(10)

print(dim0)

10


In [6]:
print(dim0.ndim)

0


In [7]:
dim0 = np.array(8)

print(f"Display 0 Dimension Array : {dim0}")

Display 0 Dimension Array : 8


In [8]:
print(f"Check dimension : {dim0.ndim}")

Check dimension : 0


<br>

### 1 Dimension Array

In [9]:
dim1 = np.array([1, 2, 3])

print(dim1)

[1 2 3]


In [10]:
print(dim1.ndim)

1


In [11]:
dim1 = np.array([10, "October", 2022])

print(f"Display 1 Dimension Array : {dim1}")

Display 1 Dimension Array : ['10' 'October' '2022']


In [12]:
print(f"Check dimension : {dim1.ndim}")

Check dimension : 1


<br>

### 2 Dimension Array

In [13]:
dim2 = np.array([[1, 2, 3], [4,5,6]])

print(dim2)

[[1 2 3]
 [4 5 6]]


In [14]:
print(dim2.ndim)

2


In [15]:
dim2 = np.array([[10, "October", 2022], ["Sat", "Sun", "Mon"]])

print(f"Display 2 Dimension Array : \n{dim2}")

Display 2 Dimension Array : 
[['10' 'October' '2022']
 ['Sat' 'Sun' 'Mon']]


In [16]:
print(f"Check dimension : {dim2.ndim}")

Check dimension : 2


<br>

### 3 Dimension

In [17]:
dim3 = np.array([[[1, 2, 3], [4,5,6]], [[7,8,9],[10,11,12]]])

print(dim3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [18]:
print(dim3.ndim)

3


In [19]:
dim3 = np.array([[["Mon", 10], ["Oct", 2022], [11, 30]]])

print(f"Display 3 Dimension : \n{dim3}")

Display 3 Dimension : 
[[['Mon' '10']
  ['Oct' '2022']
  ['11' '30']]]


In [20]:
print(dim3.ndim)

3


<br>

## Indexing Numpy Array

### 1 Dimension

In [21]:
dim1 = np.array([1, 2, 3])

print(dim1[2])

3


In [22]:
print(f"{dim1[0]} + {dim1[2]} = {dim1[0] + dim1[2]} ")

1 + 3 = 4 


<br>

### 2 Dimension

In [23]:
dim2 = np.array([[10, "October", 2022], ["Sat", "Sun", "Mon"]])

print('2nd element on 1st row:', dim2[0, 1])

2nd element on 1st row: October


In [24]:
print('1st element on 2nd row :', dim2[1,0])

1st element on 2nd row : Sat


<br>

### 3 Dimension

In [25]:
dim3 = np.array([[[1, 2, 3], [4,5,6]], [[7,8,9],[10,11,12]]])

print(dim3[0, 1, 2])

6


<br>

## Slicing Numpy Array

### 1 Dimension

In [26]:
dim1 = np.array([1, 2, 3])

print(dim1[1:])

[2 3]


In [27]:
print(dim1[:3:2])

[1 3]


<br>

### 2 Dimension

In [28]:
dim2 = np.array([[10, "October", 2022], ["Sat", "Sun", "Mon"]])

print(dim2[1, :-1])

['Sat' 'Sun']


In [29]:
print(dim2[1, 0:2])

['Sat' 'Sun']


<br>

### 3 Dimension

In [30]:
dim3 = np.array([[[1, 2, 3], [4,5,6]], [[7,8,9],[10,11,12]]])

print(dim3[0, 1, 0:4])

[4 5 6]


In [31]:
print(dim3[1, 0:2, 0:3])

[[ 7  8  9]
 [10 11 12]]
